# Generated by Django 2.2.16 on 2020-09-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200907_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text="13 Character <a href=https://www.isbn-international.org/content/what-isbn>ISBN number</a>'", max_length=13, verbose_name='ISBN'),
        ),
    ]
